### ISSUE TITLE
25 March 2020 - Team 101 - The Crux - Peer to Peer Review

### ISSUE THREAD

**Issue by fdfragoso** [MuriloRoque/Newsweek-Clone#3]
Great job! The projects look amazing!

Recommendations;

- JS for bootstrap should be on the bottom of the body - lines 12, 13, 14.
- Remember of bootstrap classes;
- The search on navbar have some bar when clicked - use outline: none;

**Comment by MuriloRoque** [comment]
Made the changes and close the issue.

Thank you, team!
